// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYsZhBY4gFtTAS-dEVMoJ01ei_Ogmlk-U',
    appId: '1:286797711898:web:fc25ced178e91479aa9fa3',
    messagingSenderId: '286797711898',
    projectId: 'fir-flutter-auth-51d0b',
    authDomain: 'fir-flutter-auth-51d0b.firebaseapp.com',
    storageBucket: 'fir-flutter-auth-51d0b.appspot.com',
    measurementId: 'G-1BCFFX780D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfMzDqKEgD2Tkj7hb9ufu_8MbYLFGiLD0',
    appId: '1:286797711898:android:acaee1ee16b12c80aa9fa3',
    messagingSenderId: '286797711898',
    projectId: 'fir-flutter-auth-51d0b',
    storageBucket: 'fir-flutter-auth-51d0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG8LjUFqbkxNRxdkiMxOp6Re7jUolrHpI',
    appId: '1:286797711898:ios:7a07e40de4364637aa9fa3',
    messagingSenderId: '286797711898',
    projectId: 'fir-flutter-auth-51d0b',
    storageBucket: 'fir-flutter-auth-51d0b.appspot.com',
    iosBundleId: 'com.example.firebaseCleanArchitectureAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG8LjUFqbkxNRxdkiMxOp6Re7jUolrHpI',
    appId: '1:286797711898:ios:7a07e40de4364637aa9fa3',
    messagingSenderId: '286797711898',
    projectId: 'fir-flutter-auth-51d0b',
    storageBucket: 'fir-flutter-auth-51d0b.appspot.com',
    iosBundleId: 'com.example.firebaseCleanArchitectureAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYsZhBY4gFtTAS-dEVMoJ01ei_Ogmlk-U',
    appId: '1:286797711898:web:7b23957fed7bd119aa9fa3',
    messagingSenderId: '286797711898',
    projectId: 'fir-flutter-auth-51d0b',
    authDomain: 'fir-flutter-auth-51d0b.firebaseapp.com',
    storageBucket: 'fir-flutter-auth-51d0b.appspot.com',
    measurementId: 'G-LF6KXDHM3R',
  );
}
